const citiesData = [
    { name: "New York", temperature: 20, airQuality: 25 },
    { name: "London", temperature: 18, airQuality: 30 },
    { name: "Tokyo", temperature: 25, airQuality: 20 },
    { name: "Accra", temperature: 25, airQuality: 20 },
    { name: "Tema", temperature: 25, airQuality: 20 },
    { name: "Kumasi", temperature: 25, airQuality: 20 },
    { name: "Oyibi", temperature: 25, airQuality: 20 },
    { name: "Texas", temperature: 25, airQuality: 20 },
    { name: "Ohio", temperature: 25, airQuality: 20 },
    { name: "Madina", temperature: 25, airQuality: 20 },
    { name: "Abuja", temperature: 25, airQuality: 20 },
    { name: "Lome", temperature: 25, airQuality: 20 },
    { name: "Lagos", temperature: 25, airQuality: 20 },
    { name: "Abijan", temperature: 25, airQuality: 20 },
    { name: "Tunis", temperature: 25, airQuality: 20 },
    { name: "Rabat", temperature: 25, airQuality: 20 },
    { name: "Kigali", temperature: 25, airQuality: 20 },
    { name: "Oslo", temperature: 25, airQuality: 20 },
    { name: "Cape Town", temperature: 25, airQuality: 20 },
    { name: "Johanesburg", temperature: 25, airQuality: 20 },
    { name: "Pretoria", temperature: 25, airQuality: 20 },
    { name: "Ipswich", temperature: 25, airQuality: 20 },
    { name: "Nagano", temperature: 25, airQuality: 20 },
    { name: "Ottawa", temperature: 25, airQuality: 20 },
    { name: "Sunderland", temperature: 25, airQuality: 20 },
    { name: "Manchester", temperature: 25, airQuality: 20 },
    { name: "Norwich", temperature: 25, airQuality: 20 },
    { name: "Beijing", temperature: 25, airQuality: 20 },
    { name: "Turin", temperature: 25, airQuality: 20 },
    { name: "Madrid", temperature: 25, airQuality: 20 },
    { name: "Barcelona", temperature: 25, airQuality: 20 },
    { name: "Lisbon", temperature: 25, airQuality: 20 },
    { name: "Dubai", temperature: 25, airQuality: 20 },
    { name: "Riyahd", temperature: 25, airQuality: 20 },
    { name: "Rio", temperature: 25, airQuality: 20 },
    { name: "Milan", temperature: 25, airQuality: 20 },
    { name: "Port Harcourt", temperature: 25, airQuality: 20 },
    { name: "Bamako", temperature: 25, airQuality: 20 },
     
  ];
  export default citiesData;